### ISSUE TITLE
rofimoji not executable by default

### ISSUE THREAD

**Issue by lockejan** [fdw/rofimoji#33]
> # From sources
> 
> Download the src directory. In the picker subdirectory, execute python setup.py install --user. This also installs the python dependencies xdg and configargparse.

This doesn't seem to be accurate anymore. One have to execute the script in `src`, not in `picker`.

---

It then got installed under:
`~/.local/lib/python3.8/site-packages/`

So far so good, but I also had to manually make the `rofimoji.py` script executable afterwards, because the installer didn't.

Furthermore I had to manually add an alias to my zsh-config to reach it for execution.

I have the feeling this isn't the intended way to go at all but more some lucky hackyish solution.

**Expected behaviour**:
- To not have to do all the manual steps described above.
- To open rofimoji via shortcut or directly from rofi rather than starting it from terminal.

Maybe someone can help me out here.🙏😀
I'm on Fedora and i3wm and installed it from source.

**Comment by fdw** [comment]
First, thanks for the report and sorry for all the effort you had to invest.

I hope to find some time soon to fix the setup. But as you may have noticed, I'm quite new to Python packaging, so if you have any ideas, please share!

**Comment by fdw** [comment]
I pushed something to `master` that could fix the installation. Could you please test it? Thank you 🙂

**Comment by lockejan** [comment]
Thanks for the feedback. 
I just tested it and this seems to solve the execution problem as well as the $PATH-appearance.
However it still doesn't work to invoke it via shortcut in i3conf, but if one put the full path to a shortcut, in my case: 
`bindsym Ctrl+Shift+d exec --no-startup-id ~/.local/bin/rofimoji` 
it works.
This has to do with i3 not recognizing dot-folders by default. I'm not sure why.
Anyway, thanks for the fix. 😀

**Comment by fdw** [comment]
If you want, you should also be able to install `rofimoji` systemwide with `sudo python setup.py install`.

**Comment by lockejan** [comment]
Ok fine. However it's not possible to trigger rofimoji inserting with ENTER. It just closes and nothing happens, but clipboard mechanisms are still working.

**Comment by fdw** [comment]
First, can you please open a new ticket for that?
Secondly, in which are you trying to type? Some, most importantly Firefox, don't work with `xdotool type` and emojis, so you have to use the clipboard workaround.

**Comment by markmandel** [comment]
Just tested this with the latest release (`pip3 install rofimoji-4.0.0-py3-none-any.whl`), and same issue - executable isn't in my path, and I had to go hunt down where rofimoji.py was being stored (I'm also not familiar with python, so if anyone else is looking it in `~/.local/lib/python3.7/site-packages/rofimoji-4.0.0-py3.7.egg/picker/rofimoji.py`)

Thanks for providing this script though! I can hack around this in the mean time with some permission changes, and harcoded paths.

**Comment by fdw** [comment]
If I understand pip/wheels correctly, you should also have `~/.local/bin/rofimoji` that is the actual executable. Can you find that?

**Comment by markmandel** [comment]
```
➜  ~ stat ~/.local/bin
stat: cannot stat '/home/markmandel/.local/bin': No such file or directory
```

:cry:

**Comment by polyzen** [comment]
Does this help at all?
https://packaging.python.org/tutorials/installing-packages/#installing-to-the-user-site

**Comment by fdw** [comment]
That's interesting. Did you use `--user`? If not, is there a `/usr/bin/rofimoji`?

All in all, this sounds like the installation from the wheel failed. Do you happen to know your `pip3` version? And I guess you're on Linux, right?

**Comment by markmandel** [comment]
I did not use `--user` -- since the docs seemed to say it was optional, so I wasn't sure why I would need it, so I didn't use it.

When I find a moment, I should take that for a spin, see if it comes out different.

```
➜  ~ pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```

And yep, on Linux. Running Debian!

**Comment by fdw** [comment]
`--user` installs the wheel only for the current user, so it would end up in `.local/bin`. Could it be that you didn't call it with `sudo` and so the installation failed? Could you please retry with `sudo pip install ...`?

**Comment by markmandel** [comment]
Aha. Therein lies the rub! :raised_hands: 

I did not use `sudo`. Fixing that, I not have `rofimoji` in my path.

It would be awesome if this was explicitly called out in the docs, and that `rofimoji` will be the binary installed in your path.

**Comment by fdw** [comment]
I've added something to the readme, so maybe this helps 🙂

Hope you have fun with `rofimoji` now!
